name: wine_snob
description: A Flutter shell for some Generative AI experiments.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_ai: ^2.1.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_ui_auth: ^1.16.1
  firebase_ui_firestore: ^1.7.1
  firebase_ui_oauth_google: ^1.4.1
  flutter_riverpod: ^2.6.1
  go_router: ^15.2.0
  google_sign_in: ^6.3.0
  http: ^1.3.0
  image_picker: ^1.1.2
  riverpod_annotation: ^2.6.1
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
